[package]
name = "fits4"
version = "0.1.0"
edition = "2021"
description = "Pure Rust FITS v4.0 reader/writer"
license = "MIT"

[dependencies.image]
version = "0.25"
optional = true

[dependencies.miniz_oxide]
version = "0.8"
optional = true

[features]
image = ["dep:image"]
gzip = ["dep:miniz_oxide"]

[profile.test]
opt-level = 3
